config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  resources :profiles, only: [:show, :edit, :update]

  concern :commentable do
    resources :comments
  end


  concern :votable do
    post :voteup, on: :member, action: :vote, rate: 1
    post :votedown, on: :member, action: :vote, rate: -1
  end

  resources :questions do
    concerns [:commentable, :votable]
    resources :answers
  end

  resources :answers, only: [] do
    concerns [:commentable, :votable]
    patch :thebest, on: :member, action: :mark_the_best
  end

  get '/search', to: 'finder#search', as: 'search'

  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
      end
      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create]
      end
    end
  end

  root to: 'questions#index'

end

app/models/question.rb
class Question < ActiveRecord::Base

  attr_writer :tag_names

  before_save :save_tag_names

  validates :title, length: { minimum: 15 }
  validates :title, presence: true
  validates :body, presence: true

  belongs_to :user
  has_many :answers, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :attachments, as: :attachmentable, dependent: :destroy
  has_many :taggings
  has_many :tags, through: :taggings
  has_many :votes, as: :votable, dependent: :destroy

  accepts_nested_attributes_for :answers
  accepts_nested_attributes_for :attachments, allow_destroy: true
  has_many :votes, as: :votable, dependent: :destroy

  is_impressionable counter_cache: true, column_name: :unique_views, unique: :all

  default_scope { order(created_at: :asc) }

  def tag_names() @tag_names || tags.pluck(:name).join(' ') end

  def voted_by?(user) Vote.exists? user: user, votable: self end

  def best_answer() answers.the_best.first end

  def summary_votes() votes.sum :voice end

  def update_answers_stat
    self.answers_stat = answers.size
    self.save!
  end

  def update_votes_stat
    self.votes_stat = summary_votes
    self.save!
  end

  def vote(user, rate)
    unless voted_by? user
      vote = self.votes.build(user: user, voice: rate*2)
      vote.save!
    end
  end

  def save_tag_names
    if @tag_names
      self.tags = @tag_names.split.map { |name| Tag.where(name: name).first_or_create! }
    end
  end

end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  respond_to :json

  def index
    respond_with collection, meta: { timestamp: collection.last.created_at }
  end

  def show
    respond_with resource, except: :answers
  end

  protected

  def create_resource(object)
    object.user = current_resource_owner
    super
  end

  def question_params
    params.require(:question)
      .permit(:title, :body)
  end

end

app/controllers/questions_controller.rb
class QuestionsController < InheritedResources::Base
  before_action :authenticate_user!, only: [:new, :create, :vote]
  impressionist actions: [:show], unique: [:impressionable_type, :impressionable_id ,:session_hash]
  load_and_authorize_resource
  skip_load_and_authorize_resource only: :index
  respond_to :js
  custom_actions resource: [:vote]
  before_action :set_author, only: [:create]

  def create
    create! notice: 'Ваш вопрос успешно размещен.'
  end

  def vote
    resource.vote(current_user, params[:rate])
  end

  protected

  def collection
    @questions ||= end_of_association_chain.paginate(:page => params[:page], :per_page => 10)
  end

  def set_author
    build_resource.user = current_user
  end

  def question_params
    params.require(:question)
      .permit(:title, :body, :tag_names, attachments_attributes: [:id, :file, :_destroy])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def can_vote?(votable)
    can?(:vote, votable) && !votable.voted_by?(current_user)
  end

  def sign_in_author?(question, user=current_user)
    user == question.user
  end
end

app/views/questions/_actions.html.slim
=link_to('Комментировать', new_question_comment_path(resource), remote: true) if can? :create, Comment
=link_to(' | Редактировать', edit_question_path(resource)) if can? :update, resource
=link_to(' | Удалить', resource, data: {:confirm => "Вы уверены, что хотите удалить вопрос\n и все, что с ним связано?"}, method: :delete) if can? :destroy, resource

app/views/questions/_answer_form.html.slim
= form_for [@question, @answer], remote: true do |f|
  .field
    = f.label :body, 'Ответ'
    br
    .js-answer-errors
    = f.text_area :body
  = f.submit 'Сохранить'
  = button_to 'Отмена', question_answers_path, question: @question, remote: true if @answer.persisted?

app/views/questions/_answers.html.slim
-@question.answers.each do |answer|
  .answer
    =answer.body
  .edit-answer*{ :id => "js-answer-#{answer.id}" }
    .actions
      -if answer.persisted? && user_signed_in?
        = link_to 'Комментировать', new_answer_comment_path(answer),remote: true
        -if answer.user == current_user
          '|
          = link_to 'Редактировать',edit_question_answer_path(answer.question, answer),remote: true
          '|
          =link_to 'Удалить', answer, data: {:confirm => 'Вы уверены, что хотите удалить ответ?'}, :method => :delete
    .js-answer-comments.comments
      =render partial: 'questions/comment', collection: answer.comments
    .js-answer-comment-form

app/views/questions/_form.html.slim
=nested_form_for resource do |f|
  .field
    =f.label :title, 'Заголовок'
    =f.text_field :title
  .field
    =f.label :body,'Содержание'
    =f.text_area :body
  .field
    =f.label :tag_names,'Метки'
    =f.text_field :tag_names
  |Вложения:
  br
  =f.fields_for :attachments do |a|
    -if a.object.new_record?
      =a.label :file, 'Файл'
      =a.file_field :file
    -else
      = link_to a.object.file.identifier, a.object.file.url
    =a.link_to_remove 'Удалить'
    br
  =f.link_to_add "Добавить файл", :attachments
  br

  =f.submit 'Сохранить', :class => 'btn-primary'
  '
  = link_to t('.cancel', :default => t("helpers.links.cancel")), questions_path, :class => 'btn'

app/views/questions/_reputation.html.slim
-if can_vote? resource
  =link_to voteup_question_path(resource), remote: true, id: 'question-vote-up', title: 'Оценить вопрос, как полезный', method: 'POST' do
      i.icon-sort-up.icon-2x
.rating
  =resource.summary_votes
-if can_vote? resource
  =link_to votedown_question_path(resource), remote: true, id: 'question-vote-down', title: 'Оценить вопрос, как бесполезный', method: 'POST' do
      i.icon-sort-down.icon-2x

app/views/questions/edit.html.slim
h1 Редактирование вопроса
=render 'form'
=link_to 'Отмена', question_path(resource)

app/views/questions/index.html.slim
= form_tag search_path, method: :get do
  .field
    =text_field_tag :inclusion, params[:inclusion]
    = submit_tag "Поиск", name: nil

= link_to 'Разместить вопрос', new_question_path
h1 Список вопросов
= will_paginate collection, previous_label: h("<"), next_label: h(">")
table
  tbody
  	-collection.each do |question|
  	  tr*{ :id => "question-summary-#{question.id}" }
  	    td
          .views.mini-counts
            span*{ :title => "#{question.unique_views} #{Russian.p(question.unique_views, 'просмотр', 'просмотра', 'просмотров')}"}
              =question.unique_views
          .answers_stat.mini-counts
            span*{ :title => "#{question.answers_stat} ответов"}
              =question.answers_stat
          .votes_stat.mini-counts
            span*{ :title => "#{question.votes_stat} голосов"}
              =question.votes_stat
        td=link_to question.title, question
        td=link_to('Удалить', question, data: {:confirm => "Вы уверены, что хотите удалить вопрос\n и все, что с ним связано?"}, method: :delete, class: 'btn btn-mini btn-danger') if can? :destroy, question

app/views/questions/new.html.slim
h1 Создать новый вопрос
=render 'form'

app/views/questions/show.html.slim
.js-question
  =link_to 'К вопросам', questions_path
  .row
    .span8.offset1.topic=resource.title
  .row
    .span1
      .js-reputation
        = render 'questions/reputation'
    .span8
      .body=resource.body
      ul
        = render resource.attachments
      .tags
        |Метки:
        = resource.tags.map(&:name).join(", ")
      .js-question-author
        = link_to image_tag(resource.user.profile.avatar_url(:thumb)), resource.user.profile
        = link_to resource.user.display_name, resource.user.profile
      .comments
        =render resource.comments, parent: resource
      .new-comment-form
      .actions
        =render 'questions/actions', resource: resource
.js-answers
  =render resource.answers, parent: resource
.row.new-answer-form
  .span8.offset1
    -if can? :create, Answer
      =render 'answers/form', parent: resource, resource: resource.answers.build
    -else
      br
      'Если Вы хотите ответить и оставить комментарий Вам следует 
      =link_to 'авторизоваться', new_user_session_path
      '&nbsp;или&nbsp;
      =link_to 'пройти регистрацию', new_user_registration_path

app/views/questions/vote.js.erb
$('.js-question .js-reputation').html('<%= j render 'questions/reputation' %>');