config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  resources :profiles, only: [:show, :edit, :update]

  concern :commentable do
    resources :comments
  end


  concern :votable do
    post :voteup, on: :member, action: :vote, rate: 1
    post :votedown, on: :member, action: :vote, rate: -1
  end

  resources :questions do
    concerns [:commentable, :votable]
    resources :answers
  end

  resources :answers, only: [] do
    concerns [:commentable, :votable]
    patch :thebest, on: :member, action: :mark_the_best
  end

  get '/search', to: 'finder#search', as: 'search'

  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
      end
      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create]
      end
    end
  end

  root to: 'questions#index'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  mount_uploader :avatar, AvatarFileUploader
end

app/controllers/api/v1/profiles_controller.rb
class Api::V1::ProfilesController < Api::V1::BaseController
  defaults :resource_class => User, :collection_name => 'users', :instance_name => 'user'
  respond_to :json
  actions :index
  
  def me
    respond_with current_resource_owner
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < InheritedResources::Base
  respond_to :html
  actions :show, :edit, :update

  def edit
    session[:return_to] ||= request.referer
    super
  end

  def update
    update! do |success, failure|
      success.html { flash[:success] = "Ваш профиль успешно обновлен."; redirect_to session.delete(:return_to) }
      failure.html { render :edit}
    end
  end

  protected

  def resource
    @profile ||= end_of_association_chain.find(params[:id]).decorate
  end

  def profile_params
    params.require(:profile).permit(:display_name, :real_name, :birthday, :website, :about_me, :weekly_email, :avatar, :location)
  end
end

app/views/profiles/_form.html.slim
= simple_form_for resource, :html => { :class => "form-horizontal" } do |f|
  = f.input :display_name
  = f.input :real_name
  = f.input :avatar, as: :file
  = f.input :birthday, class: "span1", as: :date, start_year: Date.today.year - 90,
                              end_year: Date.today.year - 12,
                              order: [:day, :month, :year]
  = f.input :website
  = f.input :location
  = f.input :about_me
  = f.input :weekly_email
  .form-actions
    = f.button :submit, :class => 'btn-primary'

app/views/profiles/edit.html.slim
- model_class = Profile
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/profiles/index.html.slim
- model_class = Profile
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
table class="table table-striped"
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:display_name)
      th= model_class.human_attribute_name(:real_name)
      th= model_class.human_attribute_name(:website)
      th= model_class.human_attribute_name(:location)
      th= model_class.human_attribute_name(:birthday)
      th= model_class.human_attribute_name(:about_me)
      th= model_class.human_attribute_name(:weekly_email)
      th= model_class.human_attribute_name(:avatar)
      th= model_class.human_attribute_name(:user_id)
      th= model_class.human_attribute_name(:created_at)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @profiles.each do |profile|
      tr
        td= link_to profile.id, profile_path(profile)
        td= profile.display_name
        td= profile.real_name
        td= profile.website
        td= profile.location
        td= profile.birthday
        td= profile.about_me
        td= profile.weekly_email
        td= profile.avatar
        td= profile.user_id
        td=l profile.created_at
        td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_profile_path(profile), :class => 'btn btn-mini'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), profile_path(profile), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_profile_path, :class => 'btn btn-primary'

app/views/profiles/new.html.slim
- model_class = Profile
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/profiles/show.html.slim
#profile
  =resource.avatar
  h1 =resource.display_name
  dl
    dt Рейтинг:
    dd#js-rating = resource.rating
    dt Имя пользователя:
    dd = resource.real_name
    dt Возраст:
    dd = resource.age
    dt Место нахождения:
    dd = resource.location
    dt Сайт:
    dd = resource.website
    dt Зарегистрирован:
    dd = resource.member_since
    dt О себе:
    dd = resource.about_me

- if can? :update, resource
  .form-actions
    = link_to t('.edit', :default => t("helpers.links.edit")), edit_profile_path(resource), :class => 'btn'
=link_to 'Назад', :back