config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  resources :profiles, only: [:show, :edit, :update]

  concern :commentable do
    resources :comments
  end


  concern :votable do
    post :voteup, on: :member, action: :vote, rate: 1
    post :votedown, on: :member, action: :vote, rate: -1
  end

  resources :questions do
    concerns [:commentable, :votable]
    resources :answers
  end

  resources :answers, only: [] do
    concerns [:commentable, :votable]
    patch :thebest, on: :member, action: :mark_the_best
  end

  get '/search', to: 'finder#search', as: 'search'

  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
      end
      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create]
      end
    end
  end

  root to: 'questions#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  validates :body, presence: true

  before_save :init_points

  belongs_to :user
  belongs_to :question
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :attachments, as: :attachmentable, dependent: :destroy
  has_many :votes, as: :votable, dependent: :destroy

  accepts_nested_attributes_for :attachments
  accepts_nested_attributes_for :votes

  default_scope { order(best_graid: :desc, created_at: :asc) }

  scope :the_best, -> { (where best_graid: 3) }

  def voted_by?(user)
    Vote.exists? user: user, votable: self
  end

  def vote(user, rate)
    unless voted_by? user
      vote = self.votes.build(user: user, voice: rate)
      vote.save!
    end
  end

  def summary_votes
    votes.sum :voice
  end

  def make_the_best
    self.best_graid = 3
    save!
  end

  protected

  def init_points
    check_the_first
    check_the_self_answer user
  end

  def check_the_first
    self.the_first = 1 if self.question.answers.count == 0
  end

  def check_the_self_answer(user_id)
    self.self_answer = 1 if self.question.user == self.user
  end

end

app/controllers/answers_controller.rb
class AnswersController < InheritedResources::Base
  before_action :authenticate_user!, only: [:create, :update, :destroy, :vote, :mark_the_best]
  load_and_authorize_resource
  respond_to :html, :js, :json
  belongs_to :question, optional: true
  actions :all, except: [:new, :index]

  def destroy
    destroy!{flash[:success] = "Ваш ответ удален."; parent_url }
  end

  def vote
    resource.vote(current_user, params[:rate])
  end

  def mark_the_best
    resource.make_the_best
    redirect_to resource.question
  end

  protected

  def create_resource(object)
    object.user = current_user
    super
  end

  def answer_params
    params.require(:answer).permit(:question_id, :body, attachments_attributes: [:id, :file, :_destroy])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  respond_to :json
  belongs_to :question, parent_class: Question

  def index
    respond_with collection, meta: { timestamp: collection.last.created_at }
  end

  protected

  def create_resource(object)
    object.user = current_resource_owner
    super
  end

  def answer_params
    params.require(:answer)
      .permit(:body)
  end
end

app/views/answers/_actions.html.slim
= link_to('Комментировать', new_answer_comment_path(resource),remote: true) if can? :create, Comment
= link_to(' | Редактировать',edit_question_answer_path(parent, resource),remote: true) if can? :update, resource
= link_to(' | Удалить', [parent, resource], data: {:confirm => 'Вы уверены, что хотите удалить ответ?'}, method: :delete) if can? :destroy, resource

app/views/answers/_answer.html.slim
.answer*{ :id => "js-answer-#{answer.id}" }
  .row
    .span1
      .js-reputation
        = render 'answers/reputation', parent: parent, resource: answer
    .span8
      =answer.body
      ul
        = render answer.attachments
      .js-author
        = link_to answer.user.display_name, answer.user.profile
      .edit-answer-form
      .actions
        =render 'answers/actions', parent: parent, resource: answer
      .new-comment-form
      .comments
        =render answer.comments, parent: answer

app/views/answers/_form.html.slim
= nested_form_for [parent, resource], remote: true do |f|
  .field
    = f.label :body, 'Ответ'
    br
    .js-answer-errors
    = f.text_area :body
  |Вложения:
  br
  =f.fields_for :attachments do |a|
    -if a.object.new_record?
      =a.label :file, 'File'
      =a.file_field :file
    -else
      = link_to a.object.file.identifier, a.object.file.url
    =a.link_to_remove 'Удалить'
  =f.link_to_add "Добавить файл", :attachments
  br
  = f.submit 'Сохранить'
  = f.submit 'Отмена', type: :reset

app/views/answers/_reputation.html.slim
-if can_vote? resource
  =link_to voteup_answer_path(resource), remote: true, id: "answer-vote-up-#{resource.id}", title: 'Оценить ответ, как полезный', method: 'POST' do
      i.icon-sort-up.icon-2x
.the-best
  -if ba = parent.best_answer
    -if ba == resource
      i.icon-check.icon-2x#the-best-answer
  -else
    -if can? :mark_the_best, resource
      =link_to thebest_answer_path(resource), id: "the-best-#{resource.id}", title: 'Оценить ответ, как лучшее решение вопроса', method: 'PATCH' do
          i.icon-check-empty.icon-2x
.rating
  =resource.summary_votes
-if can_vote? resource
  =link_to votedown_answer_path(resource), remote: true, id: "answer-vote-down-#{resource.id}", title: 'Оценить ответ, как бесполезный', method: 'POST' do
      i.icon-sort-down.icon-2x

app/views/answers/create.js.erb
<% if resource.errors.present? %>
  <% resource.errors.full_messages.each do |message| %>
    $('.js-answer-errors').append('<%= j message %>')
  <% end %>
<% else %>
  $('.js-answers').append("<%= j render 'answers/answer', answer: resource, question: parent  %>");
  $('form#new_answer')[0].reset();
  $('.js-answer-errors').empty();

<% end %>

app/views/answers/edit.js.erb
$("#js-answer-<%=@answer.id%> .edit-answer-form").html("<%= j render 'answers/form', question: parent, answer: resource%>");
$(".actions").hide();
$("form#new_answer").hide();

app/views/answers/update.js.erb
<% if resource.errors.present? %>
  <% resource.errors.full_messages.each do |message| %>
    $('.js-answer-errors').before('<%= j message %>')
  <% end %>
<% else %>
  $('#js-answer-<%= resource.id %>').replaceWith("<%= j render 'answers/answer', answer: resource, question: parent %>");
  $('#js-answer-<%= resource.id %> .edit-answer-form').empty();
  $(".actions").show();
  $("form#new_answer").show();
<% end %>

app/views/answers/vote.js.erb
$('<%= j "#js-answer-#{@answer.id} .js-reputation" %>').html('<%= j render 'answers/reputation', parent: @answer.question, resource: @answer %>');